url: https://2000class.unifiedtechnicalsolutions.co.uk
baseurl: ""
title: 2000 Class Association
subtitle: Probably the best entry-level family performance asymmetric sailing dinghy in the world!
description: >
  The 2000 Class Association is the official association for the 2000 sailing 
  dinghy. The 2000, previously known as the Laser 2000, is an entry-level 
  performance assymmetric sailing dinghy. The boat is sailed by serious racers
  and families alike.
author: 2000 Class Association
established: 1999
email:
  info@2000class.org
twitter:
  username: 2000class
  card: summary
facebook:
  publisher: https://www.facebook.com/2000classassociation/
social:
  links:
    - mailto:info@2000class.org
    - https://www.facebook.com/2000classassociation/
    - https://twitter.com/2000class
logo: /assets/img/logo-2000-class-association.png
licence: https://creativecommons.org/licenses/by/4.0/
lang: en_GB
future: true  # Publish future dated news and events
chart_key: Navionics_webapi_03675

permalink: pretty


pagination:
  debug: true
  enabled: true
  # permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  sort-reverse: true
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 10
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'
  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

collections:
  events:
    output: true
  sponsors:
    output: false
    sort_by: order
  venues:
    output: false
  videos:
  results:
    output: true
  gallery:
    output: true
  
    

defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: ""
      type: "results"
    values:
      layout: "result"
  - scope:
      path: ""
      type: "gallery"
    values:
      layout: "gallery"
  

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate-v2

exclude:
  - Gemfile
  - "*.ps1"
  - vendor/
