name: Jekyll site CI

on:
  push:
    branches:
      - main
      - master
#  pull_request:
#    branches:
#      - main
#      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        path: $GITHUB_WORKSPACE/main
    
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: $GITHUB_WORKSPACE/_site
    
    - name: Clear out gh-pages branch repo
      run: |
          cd $GITHUB_WORKSPACE/_site
          git rm -f -r ./
    
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v $GITHUB_WORKSPACE/main:/srv/jekyll \
        -v $GITHUB_WORKSPACE/_site:/srv/jekyll/_site \
        jekyll/builder:latest \
        /bin/bash -c "jekyll build --future"
    
    # sudo chmod needed because docker messes up permissions when building
    # touch .nojekyll makes sure Github doesn't try to revuild jekyll site
    - name: Commit to gh-pages
      run: |
          sudo chmod -R 777 $GITHUB_WORKSPACE/_site
          cd $GITHUB_WORKSPACE/_site
          touch .nojekyll
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "${{ github.event.head_commit.message }}"
          git push